language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=src/
install:
- pip install -U platformio
- platformio lib install 567 562
script:
- platformio run -e nodemcuv2_deploy
deploy:
  on:
    repo: blackhawk92/continuous-integration-test
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rUO8dH/8Dpmm/rTYibXySiwdyyGEFgFYnbB9DXIDmygdntmXp96NP2TQAxvxditEv4OghIqKAUT/O0LCu1jxSyV16H8rXdrrkPDeUlFBbGCDHl+Y5PxN+Bbk6kKf5N3Kb0bjzZ4tkF00oa7obsv6Gj/esczNiQuF8cr+IyiIQR1KhR+fpwSYXmssw6MnLvtomjQ0O6ohvPN78U/4Jy4U5T0gsah0g6OUXBpbZSx6hIS6/11gm4fO4rmPp2QZoLPyaHFsUbalcPmeMgsW8SfYVsQWdZUQFh/SYDRHeEFDCagA+6plPA1ahIIsOdcHDAPvgqWr0AYMjgRf3RLcJPr8rk5219MQ9y09d1Gq7ykr7pvsvqyd5KVunYNH4PCPn0l5ZuSfr80P/xdfCBl+BkO3gz3OCuHJX1SfZo/PpR09j9wItpd1GXw19JLOKQfbVKiNFdhioV4S8Pmp5pV5aDFcI4yGfPdyIPQTNS2JoJPUFqD7l4mxzdOI6tTFk/1A/ss2A0/1TwNpVk29WfNZRC+DSLE9CD+uUryLMkSjUxRJAvUMRYryZ+orgWzAu7/Qj0XFivBQ/NPI+JWdcqB2KdJp3KUuO8WL819/UUmeCipK9GXSnCB7b2kCiBL2OvA7oZoBKOHSwhADunFRiRj0VG/fDWMEyCnSzD7ztwfTQaXphPs=
  file: ".pioenvs/nodemcuv2_deploy/firmware.bin"
